<?php
/**
 * @file
 * education_committees.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function education_committees_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-committee-field_committee_leading_buttons'.
  $field_instances['node-committee-field_committee_leading_buttons'] = array(
    'bundle' => 'committee',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_committee_leading_buttons',
    'label' => 'Leading buttons',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-committee-field_committee_leading_text'.
  $field_instances['node-committee-field_committee_leading_text'] = array(
    'bundle' => 'committee',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_committee_leading_text',
    'label' => 'Leading text',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-committee-field_committee_paragraphs'.
  $field_instances['node-committee-field_committee_paragraphs'] = array(
    'bundle' => 'committee',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_committee_paragraphs',
    'label' => 'Content blocks',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'select',
      'allowed_bundles' => array(
        'announcements' => 'announcements',
        'callout' => 'callout',
        'events' => 'events',
        'fast_fact' => 'fast_fact',
        'featured_faculty' => -1,
        'news' => 'news',
        'slogan' => -1,
        'social' => -1,
        'text' => 'text',
      ),
      'bundle_weights' => array(
        'announcements' => 2,
        'callout' => 3,
        'events' => 4,
        'fast_fact' => 5,
        'featured_faculty' => 6,
        'news' => 7,
        'slogan' => 8,
        'social' => 9,
        'text' => 10,
      ),
      'default_edit_mode' => 'open',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Content blocks');
  t('Leading buttons');
  t('Leading text');

  return $field_instances;
}
