<?php
/**
 * @file
 * education_scholarships.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function education_scholarships_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-scholarship-body'.
  $field_instances['node-scholarship-body'] = array(
    'bundle' => 'scholarship',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Description',
    'required' => 1,
    'settings' => array(
      'display_summary' => 1,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-scholarship-field_scholarship_recipients'.
  $field_instances['node-scholarship-field_scholarship_recipients'] = array(
    'bundle' => 'scholarship',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter list of recipients as a bulleted list. Bolded year and dash, followed by unbolded first and last name.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_scholarship_recipients',
    'label' => 'Recent recipients',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 10,
      ),
      'type' => 'text_textarea',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Description');
  t('Enter list of recipients as a bulleted list. Bolded year and dash, followed by unbolded first and last name.');
  t('Recent recipients');

  return $field_instances;
}
