<?php
/**
 * @file
 * Code for the Education Paragraphs feature.
 */

include_once 'education_paragraphs.features.inc';

/**
 * Implements hook_classy_paragraphs_list_options().
 */
function education_paragraphs_classy_paragraphs_list_options($options, $field, $instance) {
  if ($field['field_name'] == 'field_paragraph_container_style') {
    $options['grey-background'] = t('Grey Background');
    $options['yellow-background'] = t('Yellow Background');
    $options['grey-border'] = t('Grey Border');
  }

  return $options;
}

/**
 * Implements hook_field_widget_form_alter().
 */
function education_paragraphs_field_widget_form_alter(&$element, &$form_state, $context) {
  if ($context['field']['field_name'] == 'field_announcements_view') {
    // Do not show the view name selector.
    $element['vname']['#access'] = FALSE;

    // Do not show the arguments field.
    $element['vargs']['#access'] = FALSE;

    // Do not show the token options.
    $element['token_help']['#access'] = FALSE;
  }
}

/**
 * Implements hook_entity_presave().
 */
function education_paragraphs_entity_presave($entity, $type) {
  if ($type == 'paragraphs_item' && $entity->bundle == 'announcements') {
    // Pass term and nid IDs as arguments to the Announcements paragraph view.
    $announcement_categories_tids = array();
    if (!empty($entity->field_announcement_categories['und'])) {
      foreach($entity->field_announcement_categories['und'] as $delta) {
        $announcement_categories_tids[] = $delta['tid'];
      }
    } else {
      $announcement_categories_tids[] = 'all';
    }

    $audiences_tids = array();
    if (!empty($entity->field_announcement_audience['und'])) {
      foreach($entity->field_announcement_audience['und'] as $delta) {
        $audiences_tids[] = $delta['tid'];
      }
    } else {
      $audiences_tids[] = 'all';
    }

    $affiliations_nids = array();
    if (!empty($entity->field_announcement_affiliation['und'])) {
      foreach($entity->field_announcement_affiliation['und'] as $delta) {
        $affiliations_nids[] = $delta['target_id'];
      }
    } else {
      $affiliations_nids[] = 'all';
    }

    $categories_arg = '"' . implode('+', $announcement_categories_tids) . '"';
    $audiences_arg = '"' . implode('+', $audiences_tids) . '"';
    $affiliations_arg = '"' . implode('+', $affiliations_nids) . '"';

    $args = $categories_arg . '/' . $audiences_arg . '/' . $affiliations_arg;

    $entity->field_announcements_view[LANGUAGE_NONE][0]['vargs'] = $args;
  }
}

/**
 * Implements hook_field_extra_fields().
 */
function education_paragraphs_field_extra_fields() {
  $extra['paragraphs_item'] = array(
    'slogan' => array(
      'display' => array(
        'extra_paragraph_slogan' => array(
          'label' => t('Slogan'),
          'description' => t('The slogan of the College of Education'),
          'weight' => 99,
        ),
      ),
    ),
    'social' => array(
      'display' => array(
        'extra_paragraph_social' => array(
          'label' => t('Social media'),
          'description' => t('Social media accounts of the College of Education'),
          'weight' => 99,
        ),
      ),
    ),
  );

  return $extra;
}

/**
 * Implements hook_paragraphs_item_view().
 */
function education_paragraphs_paragraphs_item_view($paragraphs_item, $view_mode, $langcode) {
  $extra = education_paragraphs_field_extra_fields();

  // Check that we're supporting the paragraph bundle being viewed.
  switch ($paragraphs_item->bundle) {
    case 'slogan':
      $field_name = 'extra_paragraph_slogan';
      _education_paragraphs_psuedo_field_visible($field_name, $view_mode, $paragraphs_item);
      $slogan_markup = "<h2 class='offscreen slogan-title'>Tagline</h2><p class='slogan'>Leaders. Scholars. Innovators.</p>";
      $paragraphs_item->content[$field_name]['#markup'] = $slogan_markup;
      break;

    case 'social':
      $field_name = 'extra_paragraph_social';
      _education_paragraphs_psuedo_field_visible($field_name, $view_mode, $paragraphs_item);
      $social_markup = "<h2 class='social-title'>Connect</h2><p class='social'>Social media accounts will be listed here.</p>";
      $paragraphs_item->content[$field_name]['#markup'] = $social_markup;
      break;

    default:
      break;
  }
}

/**
 * Check to make sure that the field is visible in this view mode.
 */
function _education_paragraphs_psuedo_field_visible($field_name, $view_mode, $paragraphs_item) {
  $config = field_bundle_settings('paragraphs_item', $paragraphs_item->bundle);
  if (empty($config['extra_fields']['display'][$field_name][$view_mode]['visible'])) {
    return;
  }
}
